- src/generate.py
> generate.py: add parse code for boolean type

- src/generate.py
> generate.py: generate right c free code

- src/generate.py
> generate.py: use local variables

- .travis.yml
> .travis.yml: new file

- src/generate.py
Generate function of parse_data and parse_file_stream, so we can parse json data of char* or file stream.
> generate parse_data and parse_file_stream

- src/generate.py
> generate.py: strip directory for header file name

- .travis.yml
- Makefile.am
- src/generate.py
> Reenable make -j

- src/read-file.c
> read-file.c: close fp

- src/generate.py
Signed-off-by: LiFeng <lifeng68@huawei.com>
> Fix memory leak when free array object

- Makefile.am
- README.md
- cfg.mk
- src/common_c.py
- src/common_h.py
- src/generate.py
- src/headers.py
- src/helpers.py
- src/sources.py
- src/validate.c
- tests/test-1.c
- tests/test-2.c
- tests/test-3.c
- tests/test-4.c
- tests/test-5.c
- tests/test-6.c
- tests/test-7.c
- tests/test-8.c
Hi, we had done some improvements for libocispec.
The main feature of the commit is to generate code according to the path of json. And we want to generate for every json found in the directory. So I can easily reuse similar structures defined in json.
Then we can use the generated sources easily in other projects.
Signed-off-by: LiFeng <lifeng68@huawei.com>
> improvements: generate the source files base on path 

- CODE-OF-CONDUCT.md
Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>
As the title says
> Code of Conduct

- src/sources.py
Fixed "Boolean items with value of False, got "lost" in JSON file" issue.
https://github.com/containers/libocispec/issues/51
> Fixed issue #51

- Makefile.am
- src/common_c.py
- src/sources.py
some refactoring.  More details in each commit.
> sources/common: code cleanup

- src/common_c.py
- src/common_h.py
- src/sources.py
Signed-off-by: wujing <wujing50@huawei.com>
> sources.py: auto free

- src/common_h.py
- src/sources.py
> src: fix comparison for pointer

- tests/test-9.c
Signed-off-by: Giuseppe Scrivano <giuseppe@scrivano.org>
> tests: define OPT_PARSE_FULLKEY if needed

- src/common_c.py
- src/common_h.py
- src/generate.py
- src/helpers.py
- src/sources.py
1. fix lose ) and \n
2. support map string int64
Signed-off-by: duguhaotian <knowledgehao@163.com>
> add map int64

- src/sources.py
> sources.py: fix unused variable warning

- src/common_c.py
> common_c: silence compiler warning

- Makefile.am
- src/headers.py
- tests/data/top_double_array_refobj.json
- tests/test-10.c
- tests/test-spec/basic/test_top_double_array_refobj.json
test data
```
[
[
{"item1": "test11", "item2": 11, "item3": true},
{"item1": "test12", "item2": 12, "item3": false}
],
[
{"item1": "test21", "item2": 21, "item3": false},
{"item1": "test22", "item2": 22, "item3": true}
]
]
```
json schema
```
$ cat tests/test-spec/basic/test_top_double_array_refobj.json 
{
"$schema": "http://json-schema.org/draft-04/schema#",
"title": "top double array of ref object",
"type": "array",
"items": {
"type": "array",
"items": {
"$ref": "test_double_array_item.json"
}
}
}
````
generate code
```
$ cat src/basic_test_top_double_array_refobj.h
// Generated from test_top_double_array_refobj.json. Do not edit!
#ifndef BASIC_TEST_TOP_DOUBLE_ARRAY_REFOBJ_SCHEMA_H
#define BASIC_TEST_TOP_DOUBLE_ARRAY_REFOBJ_SCHEMA_H
#include <sys/types.h>
#include <stdint.h>
#include …
```
> support ref for item of double array

- .gitignore
> .gitignore: update

- .github/workflows/test.yaml
- .gitmodules
- Makefile.am
- autogen.sh
- configure.ac
- src/json_common.c
- src/sources.py
- src/validate.c
- src/yajl
libyajl is unmaintained, use the new clone to include some fixes.
> yajl: statically link containers/yajl clone

- COPYING
Closes: https://github.com/containers/libocispec/issues/84
> COPYING: add bison-like exception

- README.md
Following PR adds build instructions to README.md
> Add installation and build instructions for libocispec.

- README.md
Following PR adds relevant headers missing in the samples.
> Add relevent libocispec header to samples

- src/read-file.c
* errno preserves the values set by system functions (if any)
* shrink memory where-ever possible.
* errno preserves the values set by system functions (if any)
> Optimize and retain errorcode for read-stream utils.

- Makefile.am
> Makefile.am: make sure yajl uses main branch

- src/runtime/mod.rs
> sync: add CMT and MBM fields to Intel RDT

- .github/workflows/test.yaml
Set safe directory. Just copying commit: https://github.com/containers/crun/pull/911/commits/f0cd1a7b8af24e4f810b39e11e2b10a50085ad76
> .github: set safe directory

- src/ocispec/headers.py
- src/ocispec/json_common.c
- src/ocispec/json_common.h
- src/ocispec/sources.py
- tests/test-1.c
- tests/test-10.c
- tests/test-11.c
- tests/test-3.c
- tests/test-4.c
- tests/test-5.c
- tests/test-6.c
- tests/test-7.c
- tests/test-8.c
- tests/test-9.c
Converted all the json generation code to jansson
Removed import of yajl
Will need few more PRs to cleanup.
> Converting json genration code to jansson

- .github/workflows/test.yaml
- src/ocispec/json_common.c
- src/ocispec/json_common.h
- src/ocispec/sources.py
Enable and Fix unit tests.
Refers #138
> Enable and Fix unit tests

- src/ocispec/sources.py
When we have a dummy body to avoid compiler errors
Refers #138
> Switch to jansson

- src/ocispec/json_common.c
- src/ocispec/json_common.h
- src/ocispec/sources.py
Calculate len and not get warnings
Refers #138
> Calculate of len on residual
