containers/libocispec

src/generate.py

```
'asprintf', declared with attribute warn_unused_result [-Wunused-result]
asprintf (err, "Required field %s not present", "args");
^
```

generate.py: fix the warn_unused_result

---

.gitignore
Makefile.am
src/validate.c
tests/test-1.c
tests/test-2.c

The `libocispec` current only support `runtime-spec`,
it maybe support other oci spec(oci_images_spec.h) in future.
also, `spec.h` is more common and prone to conflict.
Fix: https://github.com/giuseppe/libocispec/issues/7

rename `sepc.{h|c}` to `oci_runtime_spec.{h/c}`

---

src/generate.py

add en empty space between `free` and `(ptr)`, so we generate
similar code.

generate.py: add an empty space between 'free' and '(ptr)'

---

.gitignore
.gitmodules
Makefile.am
src/generate.py
src/validate.c
tests/image_config.json
tests/image_index_config.json
tests/image_layout_config.json
tests/image_manifest.json
tests/test-1.c
tests/test-2.c
tests/test-3.c
tests/test-4.c
tests/test-5.c
tests/test-6.c

@giuseppe This pr first make `generate.py` more generic and then add support for oci image spec, including image_spec, image_index_spec, image_layout_spec, image_manifest_spec.
Also we add test case for image spec.

libocispec: add support for oci image spec

---

src/generate.py
tests/image_index_config.json
tests/test-4.c

This PR can resolve such json-schema:
```
"os.version": {
"type": string
}
```
which is found in [image-spec/schema/image-index-schema.json](https://github.com/opencontainers/image-spec/blob/master/schema/image-index-schema.json)
and the original corresponding .c file is:
```
if (get_val (tree, "os_version", yajl_t_string))
ret->os_version = strdup (YAJL_GET_STRING (get_val (tree, "os_version", yajl_t_string)) ? : "");
```
generated error key "os_version" in get_val().
Now, it become the correct one:
```
if (get_val (tree, "os.version", yajl_t_string))
ret->os_version = strdup (YAJL_GET_STRING (get_val (tree, "os.version", yajl_t_string)) ? : "");
```
We also modify some test for the changes.

fix generate_C_parse if a key has '.', modify tests

---

.gitignore
Makefile.am
src/generate.py
tests/image_config_mapstringobject.json
tests/test-3.c
tests/test-7.c

in oci image spec, the definition for `mapStringObject` is
```
"mapStringObject": {
"type": "object",
"patternProperties": {
".{1,}": {
"type": "object"
}
}
}
```
and in the example config, the json config file as following:
```
{
"Volumes": null,
}
```
Or
```
{
"Volumes": {
"/var/lib/docker": {}
}
}
```
So we generate c code for `mapStringObject` as same as array of strings.
the array value comes from the key.

add support for type mapStringObject

---

src/generate.py
tests/test-1.c
tests/test-3.c
tests/test-4.c
tests/test-5.c
tests/test-6.c
tests/test-7.c

We think current naming of variable or function is completely generated according to json-schema, which may not conform to linux kernel naming specification. 
So we add a function "transform_to_C_name" to translate all the uppercase to lowercase, and add '_' between adjacent word if needed.

transform all the generated name to Linux Kernel Naming

---

src/generate.py
src/validate.c
tests/test-1.c
tests/test-2.c
tests/test-3.c
tests/test-4.c
tests/test-5.c
tests/test-6.c
tests/test-7.c

The current name of top struct has two repeated prefix,
such as oci_container_container, oci_image_manifest_image_manifest.
We'd better generate one prefix for the top struct, make it more
readable and simplified. Such as oci_container, oci_image_manifest

generate simplified name of top struct

---

src/read-file.c

'length' is the actually data size of buf, `buf[*length - 1] ` point to valid data, we should add '\0' after it to avoid overwrite the last Byte of buf.

read-file.c: fix overwrite the last Byte of buf

---

src/generate.py
tests/test-1.c

we got some error when parse 'anyOf' in [runtime-spec/anyOf](https://github.com/opencontainers/runtime-spec/blob/30bdf3b2b39cefe7f13b1751d37d9d397c9cfceb/schema/config-linux.json#L32):
```
typedef struct {
oci_container_namespace_reference *namespace_reference;
}
oci_container_linux_namespaces_element;
```
Because '$ref' is in cur["items"], and scan_list take it as children, this PR handle 'anyOf' like 'allOf', but not merge the results(equal to 'anychildren') of `scan_list`, and just take one of anychildren as actually children, for now, 'anyOf' only present once, so we take the 1st element as result.
```
typedef struct {
char *path;
char *type;
}
oci_container_linux_namespaces_element;
```

generate.py: fix error when parse `anyOf`

---

.gitignore
Makefile.am
src/generate.py
src/validate.c
tests/test-1.c
tests/test-2.c
tests/test-3.c
tests/test-4.c
tests/test-5.c
tests/test-6.c
tests/test-7.c

We are trying to make `generate.py` be a common script to parse any json-schema, because others have interest in using it, but have trouble with current prefix name `oci`, so we've done:
1. Reimplemented `transform_to_C_name`
2. Removed all prefix `oci` in generate.py, and transfer it by `prefix` in `Makefile.am`, then `generate.py` can be used to parse any json-schema with its own prefix, and this project still surpport `runtimespec` and `imagespec`

Parse any schema

---

src/generate.py

1. Fix segment fault if call `free(err)` when `err` is not allocated by `malloc`.
2. Fix required filed check for all generated `Node`.

Fix err required

---

Makefile.am

Current `make install` will install test programs to system, we just use them for testing, not for install.

Makefile.am: do not install test programs

---

src/read-file.c

1. Using `tmpbuf` to save return value of `realloc`, avoiding memory leak in `buf`.
2. Adding length of `'\0'` to returned `length`, or we'll get data truncation if we pack `buf` according to the returned `length`.

read-file.c: safe handle return value of realloc

---

.gitignore
Makefile.am
src/generate.py
src/read-file.c
tests/data/image_manifest_item.json
tests/test-8.c
tests/test-spec/imageManifestItems/image-manifest-items-schema.json

Close #43 
1. optimizing some code for secure issue.
2. supporting top type 'array', for this type, generating new common interface, you can see the difference in `src/image_manifest_items.c | .h` after make:
```
xxx_element **xxx_parse_file (const char *filename, struct parser_context *ctx, parser_error *err, size_t *len);
xxx_element **xxx_parse_file_stream (FILE *stream, struct parser_context *ctx, parser_error *err, size_t *len);
xxx_element **xxx_parse_data (const char *jsondata, struct parser_context *ctx, parser_error *err, size_t *len);
char *xxx_generate_json (xxx_element **ptr, size_t len, struct parser_context *ctx, parser_error *err);
```
For now, There are two limitations.
1. I don't have a better way to automatically generate `free_xxx functions`, `make_xxx functions` and …

generate.py: support parsing top type 'array'

---

src/common_c.py
src/common_h.py
src/generate.py
src/headers.py
src/helpers.py
src/sources.py

add the possibility to use the generated code with any license, as
long as the project itself is not a parser/generator.

src: add bison-like exception to the source files

---

Makefile.am

The source file src/json_common.c is listed twice in Makefile.am,
leading libtool to produce an archive with duplicated symbols. This
change removes the duplicate source.
This was introduced in commit 2e318803a2c49521ea448e3ae010b1564a7e95ed
Signed-off-by: Bruce Guenter <bruce@untroubled.org>

De-duplicate json_common in Makefile.am

---

Makefile.am
src/common_c.py
src/common_h.py
src/generate.py
src/headers.py
src/sources.py
tests/data/residual_image_layout_config.json
tests/test-9.c

some scenes need keep all json data, and pass to other handler. Such as CNI, spec of CNI only support basic member, but all plugins of [CNI extend member of network conf.](https://github.com/containernetworking/cni/blob/master/SPEC.md#network-configuration)
So, we need keep all json keys and values.

support keep all keys and values even unkonwn

---

src/common_c.py
src/sources.py
tests/test-9.c

before
```
$ valgrind --leak-check=full  ./tests/test-9
==30662== Memcheck, a memory error detector
==30662== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==30662== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==30662== Command: ./tests/test-9
==30662== 
gen error src/json_common.c: gen_yajl_val: 83: error generating json, errcode: 0
{
"imageLayoutVersion": "1.0.0",
"residual_int": 1,
"residual_float": 1.1,
"residual_string": "residual",
"residual_true": true,
"residual_false": false,
"residual_array": [
1,
2,
3,
4,
5,
6
],
"residual_obj": {
"key1": "value1",
"key2": "value2",
"key3": "value3"
}
}
==30662== 
==30662== HEAP SUMMARY:
==30662==     in use at exit: 1,437 bytes in 54 blocks
==30662==   total heap usage: 197 allocs, 143 frees, 26,576 …
```

fix memory leak

---

src/sources.py
tests/test-10.c

use valgrind check memory leak of test-10
```
$ valgrind --fair-sched=yes --tool=memcheck --leak-check=yes -v --track-origins=yes ./tests/test-10 
==76411== Memcheck, a memory error detector
==76411== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==76411== Using Valgrind-3.15.0-608cb11914-20190413 and LibVEX; rerun with -h for copyright info
==76411== Command: ./tests/test-10
==76411== 
--76411-- Valgrind options:
--76411--    --fair-sched=yes
--76411--    --tool=memcheck
--76411--    --leak-check=yes
--76411--    -v
--76411--    --track-origins=yes
--76411-- Contents of /proc/version:
--76411--   Linux version 5.4.0-52-generic (buildd@lgw01-amd64-060) (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)) #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020
--76411-- 
--76411-- Arch …
```

fix memory leak of double array

---

.gitignore
Makefile.am
src/generate.py
src/json_common.c
src/json_common.h

increase granularity for the make rules and solve a problem with
multiple targets writing to the same output files.
Closes: https://github.com/containers/libocispec/issues/70

build: split automake rules

---

src/sources.py

fix a crash with a malformed input such as:
...
"additionalGids": [
0,
1,
2,
3,
{
}
...
Found with honggfuzz.

sources.py: check for numeric type

---

.github/workflows/test.yaml

Following PR makes sure that we dont break libocispec tests executed by crun.

Add -Wextra to workflow maintain parity with crun.

---

Cargo.toml
Makefile.am
README.md
rust-gen.js
src/image/mod.rs
src/lib.rs
src/runtime/mod.rs
src/serialize.rs

Following PR allows
* Generate fresh rust types using `make generate-rust`
* Pre-built types are added in `src` to supports direct usage of libocispec in rust projects however its not neccessary.
```toml
[dependencies]
libocispec = { git = "https://github.com/containers/libocispec", branch = "master" }
```

Add rust bindings/generators for libocispec

---

README.md
src/serialize.rs

**Update serializer to indent json before writing to file**
`Reason:`  As of now libocispec rust binding's `Spec::save` is dumping all the json in a single line with no indentation at all. This PR fixes that.
**Update docs : Encourage old cargo users to point libocispec dependency to `main` insead of `master`.**
`Reason:`
Cargo version older then `0.51.0` would fail even for 
```bash
libocispec = { git = "https://github.com/containers/libocispec" }
```
with error 
``` bash
Caused by:
failed to load source for dependency `libocispec`
Caused by:
Unable to update https://github.com/containers/libocispec
Caused by:
failed to find branch `master`
Caused by:
cannot locate remote-tracking branch 'origin/master'; class=Reference (4); code=NotFound (-3)
```

Rust bindings: Update serializer to indent json before writing to file & update docs to use `main` branch for old cargo users. 

---

Makefile.am
src/json_common.c
tests/data/null_value_config.json
tests/test-11.c

```bash
$ ./tests/test-11 
gen error src/json_common.c: gen_yajl_val_obj: 23: error generating json, errcode: 1
$ ./tests/test-11 
{
"imageLayoutVersion": "1.0.0",
"just-key": null,
"obj-item": {
"key1": null
}
}
```
Signed-off-by: duguhaotian <knowledgehao@163.com>

fix bug when contain null value in json

---

configure.ac

configure scripts need to be usable with a POSIX-compliant /bin/sh
(like e.g. 'dash', which is the default provider of /bin/sh on Debian).
This has no effect on bash compatibility and will continue to work
with bash.
Signed-off-by: Sam James <sam@gentoo.org>

build: fix bashism in configure.ac

---

src/sources.py

fix a regression caused by fc5709523c5dacd2240ee28f1dfa2c3fd702e80d
that is causing the compilation to error out with `-Wall -Werror'.

src: fix regression

---

cfg.mk
maint.mk
src/sources.py
tests/data/config.json
tests/test-1.c

if an array or a dict is specified but it is empty, still allocate
it.

parser: allocate empty arrays

---

diff
src/runtime/mod.rs

Sync from upstream runtime-spec which adds new field `domainname`
to the spec.

rust, runtime: sync and add `domainname` to spec from upstream.

---

src/runtime/mod.rs

* Renames `GidMapping`, `UidMapping` -> `LinuxUidMapping` and `LinuxGidMapping`
* Adds `idle` type to `CPU` to `LinuxResources.CPU`: https://github.com/opencontainers/runtime-spec/pull/1146
* Adds `MountUidMapping` and `MountGidMapping`: https://github.com/opencontainers/runtime-spec/pull/1143

rust: add `IDMapping` for mountpoints and add `idle` type to CPU.

---

.gitignore
Makefile.am
configure.ac
ocispec.pc.in

After the changes in this PR, following the installation instructions in the [README.md](https://github.com/containers/libocispec/tree/65bdde6f82b5ce8cddc316b8f93e30bc1c35e333#installation):
```
./autogen.sh
./configure --enable-libocispec-install
make
sudo make install
```
will actually install the library, header files, and a `pkgconfig` file, as long as you call `configure` with the `--enable-libocispec-install` option. Maybe I should also update the README.md?

Make libocispec installable

---

src/image/mod.rs
src/runtime/mod.rs

- `linux` add support for `time_offsets`
- `cpu` add `burst`
- `LinuxUidMapping` add `time`

rust: sync `runtime-spec` and `image-spec`

---

src/ocispec/headers.py

by grouping the _present tags together in the generated C  header, the resulting C structure can be packed more efficiently, reducing memory usage.

libocispec: write _present tags together

---

src/ocispec/generate.py
src/ocispec/headers.py
src/ocispec/sources.py

Hello!
I want to introduce some updates to string handling: move from %s formatting to f-string.
That makes the code a bit more readable and faster.
Also, I changed how source and header files are written (basically, I just moved to the `writelines` method).
I hope you will find those changes useful.

Update formatting for source and header files

---

src/ocispec/generate.py
src/ocispec/helpers.py

fix compilation error with clang++17
ocispec/runtime_spec_schema_config_schema.h contains the following code which uses the reserved c++ keyword "class":
typedef struct {
char *class;
int32_t priority;
yajl_val _residual;
unsigned int priority_present : 1;
}
Thus the code fails to compile with clang++ 17.
Fixes #132 ( https://github.com/containers/libocispec/issues/132 )

Fix clang17++ compilation

---

.github/workflows/test.yaml
Makefile.am
configure.ac

Makefile.am: distribute the src/yajl symlink

---

.github/workflows/test.yaml
.gitmodules
Makefile.am
README.md
autogen.sh
configure.ac
ocispec.pc.in

This is the first step in migrating from yajl to jansson. We now enable to link it in the same way and add it as dependency to the project.
Q: Should we merge this into a dedicated development branch or is it fine to directly target `main`?
Refers to https://github.com/containers/libocispec/issues/138

Add jansson JSON library

---

.github/workflows/test.yaml
Makefile.am
src/ocispec/json_common.c
src/ocispec/json_common.h
src/ocispec/sources.py

**Moving YAJL to Jansson**
Added a temporary function to yajl_val to json_t
converted YAJL_GET_STRING to json_string_value
converted YAJL_IS_NUMBER to json_is_number
added functions from double to various int types.
YAJL_GET_NUMBER returns string. While json_number_value returns double.

Moving From YAJL to Jansson

---

src/ocispec/json_common.c
src/ocispec/json_common.h
src/ocispec/sources.py

Generating the initial json_t instead of yajl_val and remove temporary function
Part of #138

Generate json_t from parsing the json string

---

.github/workflows/test.yaml
.gitmodules
Containerfile
Makefile.am
README.md
autogen.sh
configure.ac

Remove yajl and jansson as gitsubmodule

Switch to jansson sm Remove YAJL and Jansson

---

src/ocispec/json_common.c
src/ocispec/json_common.h
src/ocispec/sources.py
tests/data/config.json
tests/test-1.c

Fix parsing long integers
Fix #138

uint4 parsing fix

---

src/ocispec/json_common.c
tests/data/config.json
tests/test-1.c

Parsing uint64 is not clean because jansson supports only long long int which is half of long long unisigned int
Refer #138

Jansson has no support for uint64

---

src/ocispec/generate.py
src/ocispec/headers.py
src/ocispec/helpers.py
src/ocispec/sources.py

introduce support for `string->object` maps in the code generation.
This is needed to handle net_devices in the OCI runtime specs: https://github.com/containers/crun/issues/1712

ocispec: Add string-to-object map support and refactor helper classes

---

src/ocispec/sources.py

In the generated C code for cloning the object values of a mapStringObject, an 'if' statement checking for cloning failure was followed by an erroneous semicolon.
This caused the 'if' to have an empty body, leading to the subsequent 'return NULL;' being executed unconditionally in the first iteration of the value-cloning loop if the map was not empty. Consequently, cloning a mapStringObject with one or more elements would always fail prematurely when this specific path for object-values was taken.
Removing the semicolon makes the 'return NULL;' conditional upon actual cloning failure, as intended.

sources.py: fix unconditional return in map value clone
